[package]
name = "lash"
version = "0.1.0"
edition = "2021"
description = "Interactive shell for lambda expressions"
readme = "README.md"
repository = "https://github.com/jzbor/lash"

[dependencies]
rustyline = "10.0.0"
nom = "7"
