[package]
name = "lash"
version = "0.2.0"
edition = "2021"
description = "Interactive shell for lambda expressions"
readme = "README.md"
repository = "https://github.com/jzbor/lash"
license = "MIT"


[dependencies]
rustyline = "10.0.0"
nom = "7"
nom_locate = "4.0.0"
clap = { version = "3.2.21", features = ["derive"] }
colored = "2.0.0"
