[package]
name = "lash"
version = "0.2.0"
edition = "2021"
description = "Interactive shell for lambda expressions"
readme = "README.md"
repository = "https://github.com/jzbor/lash"
license = "MIT"


[dependencies]
rustyline = "10.0.0"
nom = "7"
nom_locate = "4.0.0"
clap = { version = "4.3.11", features = ["derive"] }
colored = "2.0.4"
serde = { version = "1.0.164", features = ["derive"] }
serde_yaml = "0.9.21"
humantime = "2.1.0"
