pub const STD: &str = "K	    := \\x . \\y . x;
ADD	    := \\m . \\n . \\f . \\x . m f (n f x);
NOT	    := \\p . p FALSE TRUE;
OMEGA	:= \\x . x x;
PAIR	:= \\x . \\y . \\z . z x y;
CONS	:= \\h . \\t . \\c . \\n . c h (t c n);
PRED	:= \\n . \\f . \\x . n (\\g . \\h . h (g f)) (\\u . x) (\\u . u);
AND	    := \\p . \\q . p q p;
FALSE	:= \\x . \\y . y;
ID	    := \\x . x;
S	    := \\x . \\y . \\z . x z (y z);
TRUE	:= \\x . \\y . x;
W	    := \\x . \\y . x y y;
SECOND	:= \\p . p FALSE;
ISNIL	:= \\l . l (\\h . \\t . FALSE) TRUE;
B	    := \\x . \\y . \\z . x (y z);
IFTHENELSE	:= \\p . \\a . \\b . p a b;
FIRST	:= \\p . p TRUE;
HEAD	:= \\l . l (\\h . \\t . h) FALSE;
OR	    := \\p . \\q . p p q;
C	    := \\x . \\y . \\z . x z y;
NIL	    := \\c . \\n . n;
SUCC	:= \\n . \\f . \\x . f (n f x);
MULT	:= \\m . \\n . \\f . \\x . m (n f) x;
TAIL	:= \\l . \\c . \\n . l (\\h . \\t . \\g . g h (t c)) (\\t . n) (\\h . \\t . t);
EXP	    := \\m . \\n . n m;
SUB	    := \\m . \\n . n PRED m;
";
