name: Documentation on Github Pages
on:
  push:
    tags:

permissions:
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - run: mdbook build book
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './book/book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
